[package]
name = "wallet_electrum_example"
version = "0.2.0"
edition = "2021"

[dependencies]
bdk = { path = "../../crates/bdk" }
bdk_electrum = { path = "../../crates/electrum" }
bdk_file_store = { path = "../../crates/file_store" }
