[package]
name = "wallet_electrum_example"
version = "0.2.0"
edition = "2021"

[dependencies]
bdk_wallet = { path = "../../crates/wallet" }
bdk_electrum = { path = "../../crates/electrum" }
bdk_file_store = { path = "../../crates/file_store" }
anyhow = "1"
rand = "0.8.0"
