[package]
name = "bdk_coin_select"
version = "0.0.1"
authors = [ "LLFourn <lloyd.fourn@gmail.com>" ]

[dependencies]
bdk_chain = { path = "../../crates/chain" }

[features]
default = ["std"]
std = []
